In [ ]:
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)
print("index at 0:-",s[0])
c=pd.Series([10,20,30], index=["a","b","c"])#custom indexing
print(c)
print("index at custom a is:-",c["a"])
data={"math":90,"physics":85,"chemistry":88}#dictonary
marks=pd.Series(data)
print(data)
print(marks)

0    10
1    20
2    30
3    40
dtype: int64
index at 0:- 10
a    10
b    20
c    30
dtype: int64
index at custom a is:- 10
{'math': 90, 'physics': 85, 'chemistry': 88}
math         90
physics      85
chemistry    88
dtype: int64

In [ ]:
data={
    "name":["Aman","krish","karan"],
    "age":[22,23,21],
    "marks": [85,90,88]
}
print(data)
print(type(data))
marks=pd.DataFrame(data)
print(marks) #pandas automatically adda a default index: this is called a rangeindex(starts from 0 to n-1)

{'name': ['Aman', 'krish', 'karan'], 'age': [22, 23, 21], 'marks': [85, 90, 88]}
<class 'dict'>
    name  age  marks
0   Aman   22     85
1  krish   23     90
2  karan   21     88

In [ ]:
marks=pd.DataFrame(
    data,
    index=["student1","student2","student3"] #custom indexing in pandas data frame
)
print(marks)
marks.set_index("name",inplace=True) #if we are setting inplace true it means we are changing the orginial object if we do this without
print(marks)

           name  age  marks
student1   Aman   22     85
student2  krish   23     90
student3  karan   21     88
       age  marks
name
Aman    22     85
krish   23     90
karan   21     88

In [ ]:
df=pd.DataFrame ({
     "name":["Aman","krish","karan"],
     "age":[22,23,21],
     "marks": [85,90,88]
}
 )
print(df)
print(df.head())
print(df.tail())

    name  age  marks
0   Aman   22     85
1  krish   23     90
2  karan   21     88
    name  age  marks
0   Aman   22     85
1  krish   23     90
2  karan   21     88
    name  age  marks
0   Aman   22     85
1  krish   23     90
2  karan   21     88

In [ ]:
df=pd.DataFrame({
    "name":["Aman","saurav","karan","shubham","asbhiek","sammer"],
    "age":[22,23,21,22,25,26],
    "marks": [85,90,88,90,56,70]
})
print(df.head(2))
print(df.tail(2))
print(df.shape)#columns and rows
df.info()# information about the datsets in it
print(df.columns)#colmuns names in the datasets
print(df.describe()) #giving percentile and standard deviation
print(df["name"])#selecting data of colmuns to print
df[["name","marks"]]#printing multiple colmuns data

     name  age  marks
0    Aman   22     85
1  saurav   23     90
      name  age  marks
4  asbhiek   25     56
5   sammer   26     70
(6, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   age     6 non-null      int64
 2   marks   6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes
Index(['name', 'age', 'marks'], dtype='object')
             age      marks
count   6.000000   6.000000
mean   23.166667  79.833333
std     1.940790  13.891244
min    21.000000  56.000000
25%    22.000000  73.750000
50%    22.500000  86.500000
75%    24.500000  89.500000
max    26.000000  90.000000
0       Aman
1     saurav
2      karan
3    shubham
4    asbhiek
5     sammer
Name: name, dtype: object

      name  marks
0     Aman     85
1   saurav     90
2    karan     88
3  shubham     90
4  asbhiek     56
5   sammer     70

Filtering

In [ ]:
print(df[df["marks"]>85])# inner df gives the marks data then taking before outer df only take the data which satisfy the conditins
df[(df["age"]>21)&(df["marks"]>85)]#multiple condition

      name  age  marks
1   saurav   23     90
2    karan   21     88
3  shubham   22     90

      name  age  marks
1   saurav   23     90
3  shubham   22     90

In [ ]:
#sorting by default ascending order
print(df.sort_values("marks"))#based on passed colmn name it data will be sorted
df.sort_values("age",ascending=False)#to print int he descending order

      name  age  marks
4  asbhiek   25     56
5   sammer   26     70
0     Aman   22     85
2    karan   21     88
3  shubham   22     90
1   saurav   23     90

      name  age  marks
5   sammer   26     70
4  asbhiek   25     56
1   saurav   23     90
0     Aman   22     85
3  shubham   22     90
2    karan   21     88

In [ ]:
df["age"].value_counts()#print the how many times does the data repeated in the passed colmun

age
22    2
23    1
21    1
25    1
26    1
Name: count, dtype: int64

In [ ]:
#missing data concept
#nan is for only numerical datatype
df=pd.DataFrame({
    "name":["Aman","saurav","karan","shubham",None,"sammer"],
    "age":[22,23,None,22,25,26],
    "marks": [85,None,88,90,56,None]
})
print(df)
print(df.isnull())#prints true in  missing values
print(df.isnull().sum())#prints the count of null values for each columns
print(df.dropna())#for upfate the real data we have to use the inplace true or store into new dataframe and use it
cleaned_data=df.dropna()
print(cleaned_data)

      name   age  marks
0     Aman  22.0   85.0
1   saurav  23.0    NaN
2    karan   NaN   88.0
3  shubham  22.0   90.0
4     None  25.0   56.0
5   sammer  26.0    NaN
    name    age  marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4   True  False  False
5  False  False   True
name     1
age      1
marks    2
dtype: int64
      name   age  marks
0     Aman  22.0   85.0
3  shubham  22.0   90.0
      name   age  marks
0     Aman  22.0   85.0
3  shubham  22.0   90.0