In [1]:
import pandas as pd
import numpy as np

the prblem 
data collection process was manual and flawed 
some student details are missing 
some marks were nt recoeded 
the director wants to identify the top rankers for scholarship and at risk student for remedial classes.

In [2]:
data = {
    "Name": ["Aman", "Saurav", "Karan", "Shubham","Abhishek",None, "Sameer"],
    "Age": [22, 23, None, 22, 25, 24, 26],
   "Marks": [85, None, 88, 90, 56, 72, None],
   "Subject": ["Math", "Physics", "Maths", "Chemistry", "Math", "Physics", "Chemistry"]
}
df = pd.DataFrame(data)
df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0      Maths
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5      None  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

task 1.2
check the shape of dataset

In [3]:
#check the shape of dataset 
df.shape

(7, 4)

In [4]:
#display data types of the columns
df.dtypes
df.columns

Index(['Name', 'Age', 'Marks', 'Subject'], dtype='object')

In [5]:
#generate a statistical summary(mean/minmax)for numerica; columns
df.describe().T

       count       mean        std   min    25%   50%    75%   max
Age      6.0  23.666667   1.632993  22.0  22.25  23.5  24.75  26.0
Marks    5.0  78.200000  14.254824  56.0  72.00  85.0  88.00  90.0

In [6]:
#filter and group data
#selection - create a view showing ony the name and marks column
df[['Name', 'Marks']]

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5      None   72.0
6    Sameer    NaN

In [7]:
#filtering - Select student who have scored more than 80 marks
df[df['Marks'] > 80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0      Maths
3  Shubham  22.0   90.0  Chemistry

In [8]:
#complex filtering - select student older than 22 who also score more than 80
df[(df['Age'] > 22) & (df['Marks'] > 80)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

In [9]:
#aggregation - count how many student are entrolled in each subject
df["Subject"].value_counts()

Subject
Math         2
Physics      2
Chemistry    2
Maths        1
Name: count, dtype: int64

In [10]:
#sort the dataframe by marks in decinding
df.sort_values(by='Age', ascending=False)
df.sort_values(by='Marks', ascending=False)

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0      Maths
0      Aman  22.0   85.0       Math
5      None  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry

In [11]:
#use a specific pandas function in  fiind th etop 2 highest scores (schlorship candidates) without sorting the whole dataframe
df.nlargest(2, 'Marks')

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0      Maths

In [12]:
#identify the student with the lowest marks(remedial Candidate)
df.loc[df['Marks'].idxmin()]

Name       Abhishek
Age            25.0
Marks          56.0
Subject        Math
Name: 4, dtype: object

In [13]:
#*******************
df.nsmallest(1, 'Marks')

       Name   Age  Marks Subject
4  Abhishek  25.0   56.0    Math

In [14]:
df.sort_values(by='Marks').head(1)

       Name   Age  Marks Subject
4  Abhishek  25.0   56.0    Math

In [15]:
df.isnull()

    Name    Age  Marks  Subject
0  False  False  False    False
1  False  False   True    False
2  False   True  False    False
3  False  False  False    False
4  False  False  False    False
5   True  False  False    False
6  False  False   True    False

## task : handle missing values.

In [16]:
# 1. calculate the total number of missing vause (nan) in each coloumn
df.isnull().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

In [17]:
#2 filter and display the rows where 'marks' are missing
df[df['Marks'].isnull()]

     Name   Age  Marks    Subject
1  Saurav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry

In [18]:
# create a nwe data frame called cleaned df by removing any row that contain even a single missing values
cleaned_df = df.dropna()
cleaned_df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math

In [19]:
#compare the shape of cleane_df vs original df
cleaned_df.shape , df.shape

((3, 4), (7, 4))

 # Analyze the logic

In [20]:
#1 technical q - look at the marks colunmn in your output why are the values floats(eg , 85.0) instead of integers?
# ans---->> This happens because pandas uses float64 dtype to represent missing values (NaN) in numeric columns. 
# When there are missing values, pandas must use a floating-point type to accommodate both integers and NaN values in the same column.

In [21]:
# 2 technical q  - what is the risk of using inplace = true when droping missing values?
# Risk: Using inplace=True modifies the original DataFrame directly,
#  which can lead to loss of data if the operation is not carefully planned. 
# It also makes debugging more difficult because the original data is altered in place, 
# and there's no easy way to revert changes without re-reading the original data.

In [22]:
#3 technical q - based on the data , what specific feedback should you give to the admin team regarding the "Name" column?
# Feedback: The "Name" column contains some entries that are missing or empty.
#  It is recommended to ensure all names are properly filled in and standardized(e.g., consistent capitalization, no leading/trailing spaces). 
# This will improve data quality and make analysis more reliable.